# Generated by Django 3.1.7 on 2021-02-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210225_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
